name: hico
description: Developer for Hico App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.8+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  ui_api:
    path: external_library/ui_api

  #
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  get: ^4.6.5
  rxdart: ^0.27.3
  dio: ^4.0.4

  # Notification
  firebase_core: ^2.2.0 
  firebase_analytics: ^10.0.5
  firebase_messaging: 14.0.4
  flutter_local_notifications: ^12.0.3 

  # firebase data
  cloud_firestore: ^4.0.5

  #login
  flutter_line_sdk: ^2.2.0
  firebase_auth: ^4.1.2
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^5.0.6

  shared_preferences: ^2.0.15
  shared_preferences_android: ^2.0.13
  shared_preferences_ios: ^2.1.1

  flutter_easyloading: ^3.0.0
  flutter_svg: ^1.0.3
  connectivity_plus: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  extended_image: ^6.0.2+1
  carousel_slider: ^4.0.0
  dots_indicator: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.9
  cached_network_image: ^3.2.0
  flutter_html: ^3.0.0-alpha.2

  wakelock: ^0.6.1+2
  collection: ^1.15.0
  uuid: ^3.0.5
  mime: ^1.0.1
  image_picker: ^0.8.4+5
  file_picker: ^4.3.2
  flutter_rating_bar: ^4.0.0
  pin_code_fields: ^7.3.0
  extended_masked_text: ^2.3.1

  # Border dotted
  getwidget: ^3.0.1

  # Time spinner
  flutter_time_picker_spinner: ^2.0.0

  # Date picker
  flutter_calendar_carousel: ^2.4.1
  # flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master

  # Chat
  stream_chat_flutter: ^5.1.0

  # Call
  agora_rtc_engine: ^6.0.0
  flutter_callkit_incoming: ^1.0.2+2
  
  web_socket_channel: ^2.2.0
  permission_handler: ^10.2.0
  flutter_ringtone_player: ^3.2.0
  keyboard_dismisser: ^3.0.0
  flutter_stripe: ^6.0.0
  webview_flutter: ^3.0.2
  easy_rich_text: ^1.1.0
  device_info_plus: ^4.0.0
  vibration: ^1.7.6 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/resource/assets_resources/images/app_logo.png"
  image_path_android: "lib/resource/assets_resources/images/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/resource/assets_resources/bell/
    - lib/resource/assets_resources/icons/
    - lib/resource/assets_resources/images/
    - lib/resource/assets_resources/images/service_book_online/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SVN-Jeko
      fonts:
        - asset: lib/resource/assets_resources/fonts/SVN-Jeko-Medium.ttf
        - asset: lib/resource/assets_resources/fonts/SVN-Jeko-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
